### ISSUE TITLE
OnLongClickListener

### ISSUE THREAD

**Issue by pachu123** [MOLO17/CustomizableCalendar#33]
how do i set onLongClickListener for each date

**Comment by francesco-furlan** [comment]
Hi @pachu123,
I think you should use the `onMonthCellBindView` method on your class which `implements ViewInteractor`. Remember to `return true` on the `hasImplementedMonthCellBinding` method otherwise the `onMonthCellBindView` won't be called.
If you want to maintain the same cell UI and behavior then you can use this https://github.com/MOLO17/CustomizableCalendar/blob/master/library/src/main/java/com/molo17/customizablecalendar/library/adapter/MonthAdapter.java#L103-L161

Let me know if it solves your issue, thanks!
