### ISSUE TITLE
locale days

### ISSUE THREAD

**Issue by eslamwael74** [MOLO17/CustomizableCalendar#6]
in my locale days didn't show I am from Egypt

**Comment by francesco-furlan** [comment]
Hi @eslamwael74,
the problem is that in the library after taking the short weekdays from `DateFormatSymbols`, for each day I take the first char with `nameOfDay.substring(0, 1)` and it returns this `ا`.
So to fix this i can just skip this step and print the whole string (e.g. `الاثنين`).
I'll expose a method to make the user decide how to format the day name.

**Comment by eslamwael74** [comment]
okaiii am waiting!!

Thank you.

**Comment by francesco-furlan** [comment]
ok, should be done, check `v0.1.3`.
Let me know if you like it.

**Comment by eslamwael74** [comment]
how to use it?

**Comment by francesco-furlan** [comment]
As I wrote in the `README.md`,
there are 2 new methods in the `ViewInteractor` interface:
* `String formatWeekDayName(String nameOfDay)`
Here you can format the name of the week day. 
This method is called after injectViewInteractor method of WeekDaysView. 
You should return the formatted name of the week day.

* `boolean hasImplementedWeekDayNameFormat()`
Here you should return true if you have implemented the above method (formatWeekDayName). 
This method is called after injectViewInteractor method of WeekDaysView.
